#!/bin/bash
# =============================================================================
# entrypoint.sh — AI Workspace Container Startup
# =============================================================================
# Initialization order:
#   1. Fix volume permissions (since Docker mounts them as root by default)
#   2. Bootstrap hermes-agent config (.env) pointing LLM to OmniRoute
#   3. Exec supervisord which manages all services:
#      - OmniRoute (4000)
#      - hermes-gateway (8642, waits for OmniRoute)
#      - hermes-dashboard (9119, waits for OmniRoute)
#      - hermes-workspace (3000)
#      - aionui (3005)
# =============================================================================

set -e

HERMES_HOME="${HERMES_HOME:-/opt/data}"
HERMES_ENV_FILE="$HERMES_HOME/.env"
LOG_DIR="$HERMES_HOME/logs"

# ---------------------------------------------------------------------------
# Step 1: Pre-flight checks & permissions
# ---------------------------------------------------------------------------
echo "[entrypoint] Fixing volume permissions for hermes user..."
mkdir -p "$LOG_DIR"
chown -R hermes:hermes "$HERMES_HOME" /workspace /data 2>/dev/null || true

# ---------------------------------------------------------------------------
# Step 2: Bootstrap hermes-agent config
# ---------------------------------------------------------------------------
echo "[entrypoint] Bootstrapping hermes-agent config..."

# Write hermes-agent .env — all config is driven by Docker env vars.
# OPENAI_BASE_URL points hermes-agent to OmniRoute as its LLM backend.
# OmniRoute handles routing to actual providers (OpenAI, Anthropic, etc.)
# based on the model name and configured API keys.
cat > "$HERMES_ENV_FILE" << EOF
# Auto-generated by entrypoint.sh — do not edit manually.
# Regenerated on every container start from Docker environment variables.

# ── LLM Backend ─────────────────────────────────────────────────────────────
# hermes-agent uses OmniRoute as its LLM provider.
# OmniRoute (localhost:4000) routes to actual providers using the keys below.
OPENAI_BASE_URL=http://localhost:4000/v1
OPENAI_API_KEY=${OMNIROUTE_API_KEY:-${OPENAI_API_KEY:-omniroute-internal}}

# Model hermes-agent will use (must be supported by OmniRoute/your provider)
${HERMES_LLM_MODEL:+HERMES_MODEL=${HERMES_LLM_MODEL}}
${HERMES_LLM_MODEL:-# HERMES_MODEL not set — hermes will use its default or prompt on first run}

# ── Gateway API Server ───────────────────────────────────────────────────────
API_SERVER_ENABLED=true
API_SERVER_HOST=0.0.0.0
API_SERVER_PORT=8642
$([ -n "${API_SERVER_KEY:-}" ] && echo "API_SERVER_KEY=${API_SERVER_KEY}" || echo "# API_SERVER_KEY not set — gateway runs without auth (ok for single-container)")

# ── Dashboard ────────────────────────────────────────────────────────────────
HERMES_DASHBOARD=true
HERMES_DASHBOARD_HOST=0.0.0.0
HERMES_DASHBOARD_PORT=9119

# ── Provider keys (OmniRoute reads these too via Docker env) ─────────────────
# These are passed through from Docker env vars — no need to duplicate here.
EOF

# Make sure .env belongs to hermes too
chown hermes:hermes "$HERMES_ENV_FILE" 2>/dev/null || true

echo "[entrypoint] hermes config written to $HERMES_ENV_FILE"

# ---------------------------------------------------------------------------
# Step 3: Start supervisord (manages all services)
# ---------------------------------------------------------------------------
echo "[entrypoint] Starting supervisord..."
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
