#!/bin/bash
# =============================================================================
# entrypoint.sh — AI Workspace Container Startup
# =============================================================================
# Initialization order:
#   1. Bootstrap hermes-agent config from env vars (if not already present)
#   2. Start hermes gateway (API server on :8642)
#   3. Start hermes dashboard (API on :9119)
#   4. Wait for gateway to be healthy
#   5. Exec supervisord (OmniRoute :4000, Hermes Workspace :3000, Aion UI :3005)
# =============================================================================

set -e

HERMES_HOME="${HERMES_HOME:-/opt/data}"
HERMES_ENV_FILE="$HERMES_HOME/.env"

echo "[entrypoint] Bootstrapping hermes-agent config..."

# Create hermes home directory if it doesn't exist
mkdir -p "$HERMES_HOME"

# Write hermes-agent .env config from Docker environment variables
# This enables the HTTP API server which hermes-workspace needs.
cat > "$HERMES_ENV_FILE" << EOF
# Auto-generated by entrypoint.sh — do not edit manually.
# Regenerated on every container start from Docker environment variables.
API_SERVER_ENABLED=true
API_SERVER_HOST=0.0.0.0
API_SERVER_PORT=8642
$([ -n "${API_SERVER_KEY:-}" ] && echo "API_SERVER_KEY=${API_SERVER_KEY}" || echo "# API_SERVER_KEY not set — gateway runs without auth (ok for single-container)")
HERMES_DASHBOARD=true
HERMES_DASHBOARD_HOST=0.0.0.0
HERMES_DASHBOARD_PORT=9119
EOF

echo "[entrypoint] hermes config written to $HERMES_ENV_FILE"

# Activate hermes Python venv
if [ -f "/opt/hermes/.venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    . /opt/hermes/.venv/bin/activate
fi

# Ensure hermes binary is in PATH
export PATH="/opt/hermes/.venv/bin:/usr/local/bin:$PATH"
export HOME="$HERMES_HOME"

echo "[entrypoint] Starting hermes gateway on :8642..."
hermes gateway run \
    --no-tui \
    2>/var/log/supervisor/hermes-gateway.log &
GATEWAY_PID=$!

echo "[entrypoint] Starting hermes dashboard on :9119..."
hermes dashboard \
    2>/var/log/supervisor/hermes-dashboard.log &
DASHBOARD_PID=$!

# Wait for gateway to be healthy before starting the workspace
echo "[entrypoint] Waiting for hermes gateway health check..."
MAX_WAIT=60
WAITED=0
until curl -sf http://localhost:8642/health > /dev/null 2>&1; do
    if [ $WAITED -ge $MAX_WAIT ]; then
        echo "[entrypoint] WARNING: gateway did not respond in ${MAX_WAIT}s, continuing anyway..."
        break
    fi
    sleep 2
    WAITED=$((WAITED + 2))
    echo "[entrypoint] ...waiting for gateway (${WAITED}s)..."
done

if curl -sf http://localhost:8642/health > /dev/null 2>&1; then
    echo "[entrypoint] hermes gateway is healthy!"
else
    echo "[entrypoint] hermes gateway may not be ready — proceeding anyway"
fi

echo "[entrypoint] Starting supervisord (OmniRoute, Hermes Workspace, Aion UI)..."
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
